name: ai_therapy
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI and state management
  get: ^4.6.6
  google_fonts: ^6.2.1

  # Lottie animations
  lottie: ^3.3.1


  # Speech and TTS
  speech_to_text: ^7.1.0
  flutter_tts: ^4.0.4

  # Vibration
  vibration: ^3.1.3
  #  flutter_vibrate: ^2.0.1

  # HTTP & environment variables
  http: ^1.2.3
  flutter_dotenv: ^6.0.0

  # Local storage
  get_storage: ^2.1.1

  # Animations
  flutter_animate: ^4.5.0

  # Cupertino icons
  cupertino_icons: ^1.0.6
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  camera: ^0.11.2
  permission_handler: ^12.0.1
  image_picker: ^0.8.7+5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  google_fonts: ^6.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/listening.json
    - assets/speaking.json
    - assets/fonts/
    - assets/robot.png
    - assets/ai_therapy.png
    - assets/ai2.png
    - assets/ai3.png
    - assets/ai5.png
    - assets/lottie/ai1.json
    - assets/voice_chat.png

  fonts:
    - family: Nexa
      fonts:
        - asset: assets/fonts/Nexa_Bold.otf
        - asset: assets/fonts/Nexa_Light.otf
        - asset: assets/fonts/Nexa_Regular.otf
