// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFBTfq0OhE81GThqwJbn24-ljq5PGhzs4',
    appId: '1:448449128315:web:9976aefa1077cccd2c3fde',
    messagingSenderId: '448449128315',
    projectId: 'ai-therapy-57d74',
    authDomain: 'ai-therapy-57d74.firebaseapp.com',
    storageBucket: 'ai-therapy-57d74.firebasestorage.app',
    measurementId: 'G-39B7V24RWZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHDoI-XxWZ62hY-WhJMbnsReilatXkBMc',
    appId: '1:448449128315:android:f0ba6ebbed044bbc2c3fde',
    messagingSenderId: '448449128315',
    projectId: 'ai-therapy-57d74',
    storageBucket: 'ai-therapy-57d74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHh_aKvLzGGU5o1FOBCUMgUAZfgC9o3Gw',
    appId: '1:448449128315:ios:29f4d0088997347b2c3fde',
    messagingSenderId: '448449128315',
    projectId: 'ai-therapy-57d74',
    storageBucket: 'ai-therapy-57d74.firebasestorage.app',
    iosBundleId: 'com.example.aiTherapy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHh_aKvLzGGU5o1FOBCUMgUAZfgC9o3Gw',
    appId: '1:448449128315:ios:29f4d0088997347b2c3fde',
    messagingSenderId: '448449128315',
    projectId: 'ai-therapy-57d74',
    storageBucket: 'ai-therapy-57d74.firebasestorage.app',
    iosBundleId: 'com.example.aiTherapy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFBTfq0OhE81GThqwJbn24-ljq5PGhzs4',
    appId: '1:448449128315:web:2028e2f16ff332ce2c3fde',
    messagingSenderId: '448449128315',
    projectId: 'ai-therapy-57d74',
    authDomain: 'ai-therapy-57d74.firebaseapp.com',
    storageBucket: 'ai-therapy-57d74.firebasestorage.app',
    measurementId: 'G-VL1D5NDLL0',
  );
}
